### ISSUE TITLE
Scroll with code

### ISSUE THREAD

**Issue by rsxdalv** [Angelmaneuver/wallpaper-setting#11]
I saw multiple plugins but none of them seem to support this feature - I am interested in having an image that scrolls together with the code, rather than just a static backdrop.

**Comment by Angelmaneuver** [comment]
Hi rsxdalv.

sorry. The main purpose of this extension is to set the background of the entire VSCode. Therefore, we will not add the requested functionality.

We have stopped releasing the source for this extension, but there are other extensions that set the background only for the editing area that have released their source, so you can fork them and try them out.
