### ISSUE TITLE
wallpaper not showing 

### ISSUE THREAD

**Issue by pasta022** [Angelmaneuver/wallpaper-setting#12]
I recently unstalled the wallpaper settings extension again in my vscode and whenever i select a slide or an image for my wallpaper, it doesn't show. all i see is the vscode background. 

a change i noticed was that when selecting a slide, fomerly, i would be given an input to choose my opacity between 0.5-1 but that input is no longer there

**Comment by Angelmaneuver** [comment]
Hi pasta022.

Please read it in the readme.

However, if you were using normal mode, it would be easiest to move to an extension that sets a similar wallpaper.

#10 (similar question)
