### ISSUE TITLE
Extension doesn't work on VSCode - 1.72.0

### ISSUE THREAD

**Issue by Gusb3ll** [Angelmaneuver/wallpaper-setting#5]
After I updated the VSCode the extension seem to stopped working properly, in my case it's not showing my background image that I set

##

### My VSC information

```
Version: 1.72.0 (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```
##

### My settings.json

```json
{
  "wallpaper-setting.filePath": "/Users/my_home_folder/Desktop/pic/my_pic.png",
  "wallpaper-setting.opacity": 0.95,
  "wallpaper-setting.advancedMode": true
}
```

**Comment by Angelmaneuver** [comment]
Hi Gusb3ll.
I'll answer for your issue.

In conclusion, it may be better to give up on this extension and have them switch to a similar extension.

This extension is realized by writing JavaScript to "bootstrap-window.js" and loading it when VSCode starts up, but it seem that "bootstrap-window.js" is no longer used.

It may take time to respond, and perhaps the approach this extension is taking is not feasible.

I will try to do it, but don't expect too much.

**Comment by Gusb3ll** [comment]
The main reason I used this extension because of the simplicity to get it all setup, and the fact that the picture cover your entire code & explorer section which other extensions seem can't do it very well. I really appreciate for the work you have done ❤️

**Comment by edewindt** [comment]
I noticed it stopped working and I was pretty sad, not sure if there's a way to use the old version of the repository or not

**Comment by edewindt** [comment]
Thank you!
