### ISSUE TITLE
Wallpaper in cobol

### ISSUE THREAD

**Issue by mathypathy** [Angelmaneuver/wallpaper-setting#7]
When writing cobol code in vscode The wallpaper disappears, is it possible to make it compatible with Cobol?

**Comment by Angelmaneuver** [comment]
Hi mathypathy.
I'll answer for your question.

**Prerequisites**
This extension is not language-aware.

**Answers from speculation**
1. Perhaps you are running in advanced mode
2. You are using different profile when coding cobol than you usually do

Advanced mode also requires optimize work on a per-profile basis.
You should also try to optimize the profile you are using for cobol coding.

If there are no additional questions, I'll close this issue in about week.
